### ISSUE TITLE
Snippet for interactive querying of BERT model

### ISSUE THREAD

**Issue by lintool** [castorini/birch#11]
In the README, can I have a snippet for playing with BERT interactively? I.e., fire up Python interpreter, load model, issue a query and a sentence. Should be just a few lines, right?

**Comment by zeynepakkalyoncu** [comment]
Now available in the Colab notebook.

**Comment by p-null** [comment]
Hi, thanks for your great work.
I was wondering where can I find the colab notebook to play around the birth?
