### ISSUE TITLE
Patch security issue

### ISSUE THREAD

**Issue by lintool** [castorini/birch#17]
https://github.com/castorini/birch/network/alerts

**Comment by lintool** [comment]
<img width="763" alt="Screen Shot 2019-06-13 at 10 47 43 AM" src="https://user-images.githubusercontent.com/313837/59442736-c9cad680-8dc8-11e9-904b-38c5eb5d3c63.png">

Here's the detail.

**Comment by zeynepakkalyoncu** [comment]
Closed by commit [`9f0c6ea`](https://github.com/castorini/birch/commit/9f0c6eab8c17ccf422efecd1b4157703182403aa).
