### ISSUE TITLE
TREC Microblog Tracks Data

### ISSUE THREAD

**Issue by yumoxu** [castorini/birch#24]
Hi,

Thank you for your nice work! 

I took a look at the project but did not find test collections from the TREC Microblog Tracks (Lin et al., 2014) from 2011 to 2014, which were used to fine-tune BERT as described in your paper.

Could you please kindly let me know where I could find the collections?

Best,
Yumo

**Comment by HTAustin** [comment]
You can find one version of MB track dataset here: https://github.com/jinfengr/neural-tweet-search/tree/master/data @Victor0118  Could you confirm this data is what we used for fine-tuning?

**Comment by Victor0118** [comment]
@HTAustin Yes. @yumoxu Let me know if you have more questions.

**Comment by zeynepakkalyoncu** [comment]
@yumoxu I also updated our dataset on [Zenodo](https://zenodo.org/record/3269890)  to include the TREC MB splits we used to fine-tune our models.

**Comment by yumoxu** [comment]
@HTAustin @Victor0118 @zeynepakkalyoncu Yes, it is exactly what I am looking for. Thank you very much!
