### ISSUE TITLE
BERT inference latency of CPU

### ISSUE THREAD

**Issue by lintool** [castorini/birch#3]
I'd like to get some performance figures on latency on a CPU - queries per second, latency for each individual BERT inference, etc.

**Comment by zeynepakkalyoncu** [comment]
Inference on CPU is fine for a few examples (such as part of the interactive querying), but not feasible on the entire corpus.

On Tuna where:
Socket(s):             2
Core(s) per socket:    22
Thread(s) per core:    2

Batch size 16

**Comment by zeynepakkalyoncu** [comment]
Inference on CPU is fine for a few examples (such as part of the interactive querying), but not feasible on the entire corpus.

On Tuna where:
Socket(s): 2
Core(s) per socket: 22
Thread(s) per core: 2

| Batch Size | Latency / Example |
|------------|-------------------|
| 8          | 0.35 s            |
| 16         | 0.2 s             |
| 32         | 0.125 s           |
| **64**         | **0.09 s**            |
| 128        | 0.11 s            |

**Comment by lintool** [comment]
Clarification - that's latency per BERT inference over a sentence, correct?
In Robust04, in our standard reranking experiments, how many sentences do we have to apply inference over?

**Comment by zeynepakkalyoncu** [comment]
Yes. We have ~10.6m sentences to evaluate.
