### ISSUE TITLE
How do I use birch on my own dataset?

### ISSUE THREAD

**Issue by p-null** [castorini/birch#33]
Hi, thanks for this awesome work.

The first question is about document retrieval.
I'd like to use birch as a tool so I can retrive relavent documents given a query.
I am not clear how to birch to achieve such goals after reading the readme.
Can I have more instructions? Thank you!

The second is about sentence retrieval. 
How do I use birch for sentence selection? Like what the Figure 2 describes in the 'Applying BERT to Document Retrieval with Birch', can I have the most relevant sentences in a document, given a query?

**Comment by zeynepakkalyoncu** [comment]
Hi @tingkai-zhang,

If you wish to retrieve relevant documents for a single query, you may use our interactive mode. You can find the relevant arguments under the "Interactive" title in `src/args.py`. You should set `--interactive` and specify your query with `--query`. The output will be stored in a file (with whatever you name you choose with `--interactive_name`) under `data/datasets`. I will also update the README with an example for the interactive mode shortly.

Yes, Birch uses the most relevant sentences to re-rank documents. You can print these sentences in the `calc_q_doc_bert` function in `src/eval_bert.py`.
