### ISSUE TITLE
More explaination on the readme

### ISSUE THREAD

**Issue by p-null** [castorini/birch#34]
Hi, congrats on this great work!

As a new user and not having much experience on IR research field, Please don't mind I may have some naive questions. For example:
`
python src/utils/split_docs.py --collection <robust04, core17, core18> \
--index <path/to/index> --data_path data --anserini_path <path/to/anserini/root>
`

1. what does `index` here mean, document index? If I want to use it on my own dataset, what kind of values should I put here? 

2. For 'data' (path), if I want to use my own dataset, what format should it be like? What should the data look like? 

3. `anserini_path` should be `anserini_path` folder path after I execute
 `!git clone https://github.com/castorini/anserini.git
!cd anserini && mvn clean package appassembler:assemble`, right?

Thanks for answering my questions!

**Comment by zeynepakkalyoncu** [comment]
Hi @tingkai-zhang,

Thank you for your interest in our work! I am happy to answer your questions.

1. `index` points to the Lucene index of the collection. For example, refer to the Indexing section of this Anserini regression [guide](https://github.com/castorini/anserini/blob/master/docs/regressions-robust04.md) for Robust04 to see how we index our collections.

2. `data` should contain folders `datasets`, `predictions`, etc. If you want to evaluate on your dataset, you should include a single file that contains query and sentences with the respective query and sentence IDs. For the format, see `src/utils/searcher.py` and our `*_sents.csv` files available on [Zenodo](https://zenodo.org/record/3381673).

3. That's right.

I hope this answers your questions. Please let me know if you need further clarification.
