### ISSUE TITLE
I can't find the file named robust04_rm3_5cv_sent_fields.txt

### ISSUE THREAD

**Issue by zhouhj1214** [castorini/birch#6]
I put Anserini and Birch in the same directory, and I run "./train.sh mb 5" in shell. However, it return error "FileNotFoundError: [Errno 2] No such file or directory: 'robust04_rm3_5cv_sent_fields.txt' ", and I can't find the robust04_rm3_5cv_sent_fields.txt either.

**Comment by zeynepakkalyoncu** [comment]
Thank you for your interest in Birch! Please follow the new instructions, make sure you download `robust04.csv` and let me know if you still run into errors.
